version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: koa-api
    container_name: koa-api
    restart: always
    env_file: .env
    environment:
      - API_PORT=${API_PORT=5000}
      - MONGO_HOST=${MONGO_HOST=mongo}
      - MONGO_PORT=${MONGO_PORT=27017}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '8000:5000'
    networks:
      - app-network
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    links:
      - mongo
      - redis
    depends_on:
      - mongo
    command: ./run.sh
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - ./mongodata:/data/db
  redis:
    image: redis
    container_name: redis
    restart: always
    env_file: .env
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    ports:
      - '6379:6379'
    networks:
      - app-network
    volumes:
      - ./redisdata:/var/lib/redis
    command: redis-server --requirepass ${REDIS_PASSWORD}

networks: 
  app-network:
    driver: bridge

volumes:
  mongodata:
  node_modules:
  redisdata:  